// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7Zv1_aC1CMhPT3KREfvGlb-B7xheMdY',
    appId: '1:204813291447:web:d6b70eec729e8f0ba3a232',
    messagingSenderId: '204813291447',
    projectId: 'minimalchatapp-d50d2',
    authDomain: 'minimalchatapp-d50d2.firebaseapp.com',
    storageBucket: 'minimalchatapp-d50d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS31vMlSNQO91LXJHPiFSBecrRadFqFLM',
    appId: '1:204813291447:android:d7daba420cfa0627a3a232',
    messagingSenderId: '204813291447',
    projectId: 'minimalchatapp-d50d2',
    storageBucket: 'minimalchatapp-d50d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjFU4HZPu5IYHYBc9IUjo9892s0yi1bas',
    appId: '1:204813291447:ios:e5b389c2d2540bada3a232',
    messagingSenderId: '204813291447',
    projectId: 'minimalchatapp-d50d2',
    storageBucket: 'minimalchatapp-d50d2.appspot.com',
    iosBundleId: 'com.example.minimalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjFU4HZPu5IYHYBc9IUjo9892s0yi1bas',
    appId: '1:204813291447:ios:a40a82ab7927e6b1a3a232',
    messagingSenderId: '204813291447',
    projectId: 'minimalchatapp-d50d2',
    storageBucket: 'minimalchatapp-d50d2.appspot.com',
    iosBundleId: 'com.example.minimalchat.RunnerTests',
  );
}
